import {
    VuexModule,
    Module,
    getModule,
    Mutation,
    Action
} from "vuex-module-decorators";
import store from "@/store";
import * as model from "@/store/model";
import { GenerateUrl,GetLinksForUser, GetUrl } from "./api";

@Module({
    namespaced: true,
    dynamic: true,
    name: "link",
    store
})
class LinkModule extends VuexModule {
    resp = ""
    links = [];
    // mutation to get all links generated by user currently logged in
    @Mutation
    SetLinks(resp:any){
        if(resp.status == "success")    
            return this.links = resp.message
        else
            return this.links =  [];
    }
    /* 
        return generated shorturl
        {
            status : "error/success"
            message : "response return by server"
        }
    */
    @Action
    async generate(Generate: model.Generate) {
        const response = await GenerateUrl(Generate)
        //console.log(response);
        return response;
    }
    /* 
        return orignal url for provided shorturl
        {
            status : "error/success"
            message : "response return by server"
        }
    */
    @Action
    async getUrl(url:string){
        const response = await GetUrl(url);
        //console.log(response)
        return response;
    }
    /* 
        return all shorturl for curretn logged in url
        {
            status : "error/success"
            message : "response return by server"
        }
    */
    @Action({commit:'SetLinks'})
    async getLinks(){
        const response = await GetLinksForUser();
        return response;
    }
}
export default getModule(LinkModule);
