<template>
    <div class="container-fluid">
        <br>
        <center>
            <h3 class="card"> Your Short URL(s)</h3>
        </center>
        <div v-if="links.length" class="row" style="margin:0;">
            <div class="card col-sm-4 col-xs-12" v-for="link in links" :key="link.id">
                <h3 class="card-text">
                    http://localhost:8080/{{link.hashLink}}
                </h3>
        </div>
        </div>
    </div>
</template>

<script lang="ts">
import {Vue, Component} from 'vue-property-decorator'
import link from '@/store/module/link'
import Link from '@/store/model'
@Component
export default class UserLink extends Vue{
    
    get links(){
        return link.links
    }
    /*
        calls as soon as component is created
        return array of short links generated by user
    */
    created() {
        link.getLinks()   
    }
}
</script>